import type { KeyTerm } from '@/types/contract'

function confidenceLabel(score: number): string {
  if (score >= 0.8) return 'High'
  if (score >= 0.5) return 'Medium'
  return 'Low'
}

export async function exportKeyTermsPDF(terms: KeyTerm[], contractName: string) {
  // Dynamic import — @react-pdf/renderer is client-only
  const { pdf, Document, Page, Text, View, StyleSheet } =
    await import('@react-pdf/renderer')

  const React = (await import('react')).default

  const styles = StyleSheet.create({
    page:        { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#070A0E' },
    header:      { marginBottom: 24 },
    title:       { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
    subtitle:    { fontSize: 10, color: '#4A4C4F' },
    divider:     { borderBottomWidth: 1, borderBottomColor: '#DADADB', marginVertical: 12 },
    tableHeader: { flexDirection: 'row', backgroundColor: '#FAFAFA', borderBottomWidth: 1, borderBottomColor: '#DADADB', paddingVertical: 6, paddingHorizontal: 4 },
    tableRow:    { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#F0F0F1', paddingVertical: 6, paddingHorizontal: 4 },
    colName:     { width: '20%', fontWeight: 'bold' },
    colValue:    { width: '30%' },
    colPage:     { width: '8%', textAlign: 'center' },
    colConf:     { width: '10%', textAlign: 'center' },
    colEdited:   { width: '8%', textAlign: 'center' },
    colSource:   { width: '24%', color: '#4A4C4F', fontSize: 8 },
    footer:      { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#8F9193', textAlign: 'center' },
  })

  const { createElement: e } = React

  const doc = e(
    Document,
    { title: `ContractIQ — ${contractName}`, author: 'ContractIQ' },
    e(
      Page,
      { size: 'A4', orientation: 'landscape', style: styles.page },
      // Header
      e(View, { style: styles.header },
        e(Text, { style: styles.title }, 'ContractIQ — Key Terms Report'),
        e(Text, { style: styles.subtitle },
          `${contractName} · Exported ${new Date().toLocaleDateString()} · ${terms.length} term${terms.length !== 1 ? 's' : ''}`
        )
      ),
      e(View, { style: styles.divider }),
      // Table header
      e(View, { style: styles.tableHeader },
        e(Text, { style: styles.colName }, 'Term'),
        e(Text, { style: styles.colValue }, 'Value'),
        e(Text, { style: styles.colPage }, 'Page'),
        e(Text, { style: styles.colConf }, 'Confidence'),
        e(Text, { style: styles.colEdited }, 'Edited'),
        e(Text, { style: styles.colSource }, 'Source Sentence')
      ),
      // Data rows
      ...terms.map(t =>
        e(View, { key: t.id, style: styles.tableRow, wrap: false },
          e(Text, { style: styles.colName }, t.term_name),
          e(Text, { style: styles.colValue }, t.value),
          e(Text, { style: styles.colPage }, t.page_number != null ? String(t.page_number) : '—'),
          e(Text, { style: styles.colConf }, `${confidenceLabel(t.confidence_score)} (${Math.round(t.confidence_score * 100)}%)`),
          e(Text, { style: styles.colEdited }, t.is_edited ? 'Yes' : 'No'),
          e(Text, { style: styles.colSource }, t.source_sentence)
        )
      ),
      // Footer
      e(Text, { style: styles.footer, fixed: true },
        'Generated by ContractIQ · For review purposes only — not legal advice'
      )
    )
  )

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const blob = await pdf(doc as any).toBlob()
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `${contractName.replace(/\s+/g, '-')}-key-terms.pdf`
  a.click()
  URL.revokeObjectURL(url)
}
